### PR TITLE
ExceptionsZicboS Covergroup

### PR DESCRIPTION
**Pull request by coreyqh**

### CODE REVIEW

**Comment by davidharrishmc** [comment]
The senvcfg tests didn't properly specify that menvcfg must be enabled. Seeing these coverpoints gives an idea of how to do this more comprehensively with cross products.  I've updated the two test plans to reduce the number of coverpoints while increasing the coverage. I left the old coverpoints for reference, but delete them once you have the new ones.  Sorry for the churn.  Keep your eyes out for improvements like this as you develop the coverpoints.

**Comment by coreyqh** [comment]
Updated ZicboU and ZicboS to reflect the testplan changes

**Comment by davidharrishmc** [comment]
Isn’t S mode 01

**Comment by coreyqh** [comment]
Oops, now fixed

**Pull request merged**
