### PR TITLE
Add LICENSE and other misc files to new repo

### PR DESCRIPTION
**Pull request by MikeOpenHWGroup**

### CODE REVIEW

**Comment by davidharrishmc** [comment]
The license looks good.

cvw-arch-verif seems like a funny name for this repo.  The goal is to write core-independent tests.  Would riscv-arch-verif or openhw-arch-verif be a better name?

**Review by davidharrishmc — COMMENTED** [review]
Looks good.

**Comment by ross144** [comment]
License looks good to me.  I agree with David a broader name would be more inclusive since this project's purpose is to be useful to cores beyond cvw.

**Review by ross144 — APPROVED** [review]
I approve.

**Pull request merged**
