### PR TITLE
FLI immediate coverpoint

### PR DESCRIPTION
**Pull request by coreyqh**
* Created new coverpoint that checks the 5 bits of the rs1 field in the instruction binary, making sure each of the 32 values is exercised
* All FLI instructions are getting majority (87.5%) coverage, only missing hazard coverpoints
* FLI instructions should be fully covered once hazard refactoring is completed by the HMC team

### CODE REVIEW

**Comment by davidharrishmc** [comment]
This is a bit strange to cover this instruction with cp_fs1_fli.  It doesn't take a fs1.  Would it make sense to be cp_rs1_fli instead, or a different column?

**Comment by coreyqh** [comment]
Ah, you're right. There had been an x incorrectly marking cp_fs1 before, so that is likely where this stemmed from. 

I'll change to cp_rs1_fli.

**Comment by coreyqh** [comment]
Changed to cp_rs1_fli

**Comment by davidharrishmc** [comment]
The function is still called make_fs1

**Comment by coreyqh** [comment]
Oops, I missed that last night. 

These tests are now made with `make_rs1`

**Pull request merged**
