### PR TITLE
completed c.subw

### PR DESCRIPTION
**Pull request by hamza-1821**
Added a new template for cp_rd_corners for c.subw. Some of the bins needed sign extension.

### CODE REVIEW

**Comment by Mysterio-Abdullah** [comment]
Can I add something? Instead of making another template cp_rd_corners_subw.txt, you can use exisiting template RV64_cp_rd_corners_32bit.txt and instead of passing corners you added, you can pass existing corners "corners_32bits" in testgen.py.

Let me know if it works :)

**Comment by hamza-1821** [comment]
Good thought ! might've missed them.

**Comment by Mysterio-Abdullah** [comment]
Now, its better to delete the template you wrote "cp_rd_corners_subw.txt" ig.

**Comment by davidharrishmc** [comment]
cp_rd_toggle_lui sounds like it should apply to all lui instructions, but I think it only applies to c.lui.  Can you change the name accordingly?

@Mysterio-Abdullah thank you for your review on this too!

**Comment by hamza-1821** [comment]
Done.

**Comment by hamza-1821** [comment]
For c.lui both in 32 and 64, there is one bin in cp_rd (bin auto [x2]) that remains, because x2 is invalid for c.lui so it cannot be hit. Do i need to create a template for c.lui for this 1 bin too ?

**Comment by davidharrishmc** [comment]
Looks like it.

**Comment by davidharrishmc** [comment]
Shouldn't the clui templates have 6 ones instead of just 5?  The immediate is 6 bits.

**Comment by hamza-1821** [comment]
Yes ! but we are providing c.lui with 5 bit Uimmediate value instead of 6 (it generates error for 6 bit for some reason).

**Comment by davidharrishmc** [comment]
I posted about this in the 10x channel.  It's really important to find a way to test all of the bits, rather than skip one.  Never write a coverpoint that hides something that actually needs testing. Regular lui may have a similar challenge.  Do we need a signed rather than unsigned immediate?

**Pull request closed without merging**
