### PR TITLE
Updates to RV32D testplan and RV32F testplan bugfixes

### PR DESCRIPTION
**Pull request by HamzaYusufJamal**
RV32D has been updated with the new coverpoints and syntax from 32F. I also saw that some CPs that probably should have been enabled in RV32F were not marked, so I enabled those in the testplan for 32F.

### CODE REVIEW

**Comment by davidharrishmc** [comment]
The .csv are expanded.  Please shrink them back, and test right before making the PR, which would have caught this.

**Comment by HamzaYusufJamal** [comment]
Thanks for catching that, I've collapsed the csv's and tested.

**Comment by davidharrishmc** [comment]
Merge conflict now. :(

**Comment by HamzaYusufJamal** [comment]
Merge conflict is resolved

**Comment by davidharrishmc** [comment]
@HamzaYusufJamal 

This PR introduced errors in regression related to get_gpr_c_reg.  I had to revert it.  Could you carefully reapply your changes and check if it works?  Look for errors while regression is running.

**Pull request merged**
