### PR TITLE
Update Makefile

### PR DESCRIPTION
**Pull request by jordancarlin**
Overhauled Makefile
- Does not copy priv source files to multiple locations
- Follow more standard Makefile conventions and support increased parallelism and dependency tracking
- Add support for rebuilding just the priv or unpriv tests
- Should be run using `make --jobs` now
- Single elf target that dynamically determines xlen

DO NOT MERGE until https://github.com/openhwgroup/cvw/pull/1112 is merged

### CODE REVIEW

**Comment by davidharrishmc** [comment]
cvw#1112 is merged.  Is this ready to merge?

**Comment by davidharrishmc** [comment]
Regression doesn't merge properly.  make merge works by itself.
```
~/cvw/addins/cvw-arch-verif$ regression-wally --fcov
...
wsim --sim questa --fcov rv64gc /home/harris/cvw/addins/cvw-arch-verif/tests/rv64/Zfh/WALLY-COV-ALL.elf > /home/harris/cvw/sim/questa/logs/rv64gc_Zfh_WALLY-COV-ALL.elf.log: Success
find: ‘tests/priv’: No such file or directory
find: ‘tests/priv’: No such file or directory
rm -f work/merge*.ucdb
bin/coverreport.py
make: bin/coverreport.py: No such file or directory
make: *** [/home/harris/cvw/addins/cvw-arch-verif/Makefile:91: merge] Error 127
SUCCESS! All tests ran without failures
```

**Comment by jordancarlin** [comment]
Have you pulled the latest cvw repo? That's why PR1112 was needed.

**Comment by davidharrishmc** [comment]
I thought I had, but clearly I didn’t!

**Pull request merged**
