### PR TITLE
c.sw 100% coverage

### PR DESCRIPTION
**Pull request by Mysterio-Abdullah**
100% coverage of c.sw achieved after unchecking all the coverpoints of c.lw to ensure that its each bin is getting hit because of its own tests. i.e,

Covergroup instance obj_c_lw                             0.00%        100          -    Uncovered
Covergroup instance obj_c_sw                         100.00%        100          -    Covered

### CODE REVIEW

**Comment by Mysterio-Abdullah** [comment]
Please let me know if anything can be improved :)

**Comment by davidharrishmc** [comment]
Looks reasonable.  Why have the if check, instead of just legalizing the register numbers?

**Comment by Mysterio-Abdullah** [comment]
Sir, I'm already legalizing the rs1 and rs2 in make_rs2p. If i try to legalize it again by using legalizecomp function, it will not provide all rs2p from 8 to 15.

**Comment by Mysterio-Abdullah** [comment]
I also removed cp_rs1_toggle for both c.sw and c.lw because it seems useless as we are using rs1 as a base address to load and store.

**Comment by davidharrishmc** [comment]
I presume you are saying this from experience, but I’m not seeing the problem on casual inspection.  If line 157 were gone, why wouldn’t we still cover all rs2p from 8 to 15?

**Comment by Mysterio-Abdullah** [comment]
Apologise, I also went through it again, and seems everything fine without it.

**Pull request merged**
