### PR TITLE
c.lw 100% Coverage.

### PR DESCRIPTION
**Pull request by Mysterio-Abdullah**
Managed to get 100% coverage of "c.lw"
Luckily, 100% coverage of c.sw has been achieved from the test generated for "c.lw" because I was using c.sw in them.
Should I generate separate tests for "c.sw" ?

### CODE REVIEW

**Comment by davidharrishmc** [comment]
Terrific!

Please do generate separate tests for c.sw.  We would like to be able to test each instruction independently even though some of them naturally do cover others.

**Comment by davidharrishmc** [comment]
This looks good.  There's a simplification in make_rd_rs1.  The for loops appear to be cut and paste of each other, only differing in the range.  Could you set a variable rng to either range(8,16) or range(32) based on (test in cltype), and then only have one copy of the loop, based on for r in rng?

**Comment by Mysterio-Abdullah** [comment]
Ok Sure. I'll generate individual tests for "c.sw".
Also, I simplified the make_rd_rs1. Thanks for pointing.

**Comment by davidharrishmc** [comment]
Minor issue -- the make_cmp_rd_rs1 function now has the body double-indented.

**Comment by Mysterio-Abdullah** [comment]
Sorry for that. I think everything is fine now.

**Pull request merged**
