### PR TITLE
Added my name to the respective team

### PR DESCRIPTION
**Pull request by hamza-1821**

### CODE REVIEW

**Comment by davidharrishmc** [comment]
Hamza, could you give this PR a more descriptive title?

**Comment by hamza-1821** [comment]
ok !

**Comment by davidharrishmc** [comment]
Hamza, in the Files changed tab, it looks like an image is attached.  Let's keep this simple and just do names.  Can you remove the image?

**Comment by hamza-1821** [comment]
I only added my name, I did not attach any image.
I have attached a screenshot below, can you confirm ?
Screenshot from 2024-09-04 06-07-46

**Comment by davidharrishmc** [comment]
Ah, you're all good.  The image must have come earlier.

**Pull request merged**
