### PR TITLE
Comprehensive review of hazards in all testplans

### PR DESCRIPTION
**Pull request by HamzaYusufJamal**

### CODE REVIEW

**Comment by HamzaYusufJamal** [comment]
- More comprehensive review of hazards in all testplans, testplanedit script now only rewrites files if their data is changed
- 100% hazard coverage on all non-compressed unpriv instructions. Compressed instructions will need a total refactor before they can be included in hazard testing, and this will take a considerable amount of thought and time.
- Some minor fixes to Zbb and Zbc 32/64 that bring some instructions up to 100% coverage. Some new coverpoints for these as well. Testplans still need to be reviewed carefully, as I noticed that Zbb64 is completely missing any marks in the cp_rd_toggle column.
- I have done some amount of code refactoring that was relatively straightforward to include as part of my own work, but there is still a lot of cleanup to be done here. I will be working on this some more in the coming weeks.

**Comment by HamzaYusufJamal** [comment]
Changes to make:

Uncommit makefile (pull new one and commit that)
Go through and remove unchanged csv's from the commit (same way as makefile, Zaamo, Zalrsc) 
Uncommit testplanedit (create a local copy with a new name and use git rm to remove testplanedit)
Go through unimplemented instructions and add hazard coverpoints for all of them (Zbkb, Zbkx, Zknd, Zkne, Zknh)
remove hazard coverpoints for all compressed instructions since they can't be hit (Zca, Zcb, ZcbM, ZcbZba, ZcbZbb, Zcd, Zcf)
remove ZcaZicsr.csv entirely

Unnamed column in 64I? Need to figure out why that's happening, and it's probably safe to just remove the column

**Comment by HamzaYusufJamal** [comment]
List of changes in the last commit:

Uncommit makefile
Go through and remove unchanged csv's from the commit (Zaamo, Zalrsc)
Uncommit testplanedit.py
Go through unimplemented instructions and add hazard coverpoints for all of them (Zbkb, Zbkx, Zknd, Zkne, Zknh)
Remove hazard coverpoints for all compressed instructions since they can't be hit (Zca, Zcb, ZcbM, ZcbZba, ZcbZbb, Zcd, Zcf)
Remove ZcaZicsr.csv
Remove unnamed column in RV64I.csv

**Comment by davidharrishmc** [comment]
@HamzaYusufJamal, it doesn't look like this PR contains what you thought it does.  Always review your PRs by scrolling down through the changed files to make sure your changes are the intended ones.

The Makefile is still here. So is testplanedit.

Line 981says Zicsr hazards are not implemented, but they have rw in the gpr_hazard column.

Zbkb doesn’t have coverpoints for all instructions

I haven't reviewed any of the other parts.  Please let me know when you have updated and checked that the PR matches your expectations.

**Pull request merged**
